package operators

// The flags the Flag Operator and the Region Filter can find in a name.
//
// A name is read in two passes. First the words, in flagWords order: the
// first row with a word the name carries as a substring, in any letter case
// ("xJapan" carries Japan), wins, wherever in the name the word sits ("US
// 香港" is Hong Kong). Only when no word matches are the codes tried, in
// flagCodes order: a code matches case-sensitively as a whole run of ASCII
// letters ("HK01" and "x-HK" carry HK, "SHK" does not), except that "CN"
// followed by a 2 and no letter ("CN2", "CN2 01") is the CN2 carrier, not
// China. A word always beats a code: "Virginia BY" is the United States,
// not Belarus. The first word row is not a country: the bundle gives
// provider notices (traffic, expiry) the rainbow flag, ahead of every
// country.
//
// The rows are what the pinned bundle (2.36.22) answers, observed through
// engine.convert over synthetic names: every two- and three-letter code, the
// English and Chinese names of every country, world cities and regions, and
// every keyword below in each letter case and beside letters, digits and
// punctuation. Each keyword is the shortest substring of a recognised name
// that the bundle still recognised; each order is the one every pair of rows
// showed, and neither depends on where in the name a keyword sits.
// TestFlagOperatorMatchesBundleOnKeywordVocabulary in package main holds the
// tables to the bundle. A name carrying a keyword the vocabulary did not
// contain gets the pirate flag here and may get a country from the bundle.

var flagWords = []struct {
	flag  string
	words []string
}{
	{"🏳️‍🌈", []string{"bandwidth", "expire", "时间", "流量", "过期"}},
	{"🇸🇱", []string{"应急"}},
	{"🇲🇵", []string{"northern mariana islands", "saipan", "北马里亚纳", "塞班"}},
	{"🇸🇴", []string{"mogadishu", "somalia", "索马里"}},
	{"🇦🇶", []string{"antarctica", "南极"}},
	{"🇦🇬", []string{"antigua and barbuda", "安提瓜和巴布达"}},
	{"🇬🇱", []string{"greenland", "格陵兰"}},
	{"🇿🇼", []string{"zimbabwe", "津巴布韦"}},
	{"🇦🇼", []string{"aruba", "阿鲁巴"}},
	{"🇲🇱", []string{"mali", "马里"}},
	{"🇦🇩", []string{"andorra", "安道尔"}},
	{"🇦🇪", []string{"dubai", "united arab emirates", "迪拜", "阿联酋"}},
	{"🇦🇫", []string{"afghanistan", "阿富汗"}},
	{"🇦🇱", []string{"albania", "阿尔巴尼亚", "阿爾巴尼亞"}},
	{"🇦🇲", []string{"armenia", "亚美尼亚"}},
	{"🇦🇷", []string{"argentina", "阿根廷"}},
	{"🇦🇹", []string{"austria", "奥地利", "奧地利", "维也纳"}},
	{"🇼🇸", []string{"samoa", "萨摩亚", "薩摩亞"}},
	{"🇦🇺", []string{"australia", "sydney", "墨尔本", "悉尼", "澳大利亚", "澳洲"}},
	{"🇦🇿", []string{"azerbaijan", "阿塞拜疆"}},
	{"🇧🇦", []string{"bosnia and herzegovina", "波黑"}},
	{"🇧🇩", []string{"bangladesh", "孟加拉"}},
	{"🇧🇪", []string{"belgium", "比利时", "比利時"}},
	{"🇧🇬", []string{"bulgaria", "保加利亚", "保加利亞"}},
	{"🇧🇭", []string{"bahrain", "巴林"}},
	{"🇧🇷", []string{"brazil", "圣保罗", "巴西"}},
	{"🇧🇳", []string{"brunei", "文莱", "汶萊"}},
	{"🇧🇾", []string{"belarus", "白俄"}},
	{"🇧🇴", []string{"bolivia", "玻利维亚"}},
	{"🇧🇹", []string{"bhutan", "不丹"}},
	{"🇨🇦", []string{"canada", "toronto", "加拿大", "多伦多", "温哥华", "蒙特利尔"}},
	{"🇨🇫", []string{"central african republic", "中非"}},
	{"🇨🇭", []string{"switzerland", "zurich", "瑞士", "苏黎世"}},
	{"🇨🇱", []string{"chile", "智利"}},
	{"🇨🇴", []string{"colombia", "哥伦比亚"}},
	{"🇨🇷", []string{"costa rica", "哥斯达黎加"}},
	{"🇨🇾", []string{"cyprus", "塞浦路斯"}},
	{"🇨🇿", []string{"czech", "捷克"}},
	{"🇩🇪", []string{"frankfurt", "german", "德国", "德國", "法兰克福"}},
	{"🇩🇰", []string{"denmark", "丹麥", "丹麦"}},
	{"🇩🇿", []string{"algeria", "阿尔及利亚", "阿爾及利亞"}},
	{"🇪🇨", []string{"ecuador", "厄瓜多尔"}},
	{"🇪🇪", []string{"estonia", "爱沙尼亚"}},
	{"🇪🇬", []string{"egypt", "埃及"}},
	{"🇪🇸", []string{"spain", "西班牙"}},
	{"🇪🇺", []string{"european union", "欧盟"}},
	{"🇫🇮", []string{"finland", "芬兰", "芬蘭", "赫尔辛基"}},
	{"🇫🇷", []string{"france", "巴黎", "法国", "法國"}},
	{"🇬🇧", []string{"england", "great britain", "london", "united kingdom", "伦敦", "英"}},
	{"🇬🇪", []string{"georgia", "格鲁吉亚"}},
	{"🇬🇷", []string{"greece", "希腊", "希臘"}},
	{"🇬🇺", []string{"guam", "关岛", "關島"}},
	{"🇬🇹", []string{"guatemala", "危地马拉"}},
	{"🇭🇰", []string{"hong kong", "hongkong", "港"}},
	{"🇭🇷", []string{"croatia", "克罗地亚"}},
	{"🇭🇺", []string{"hungary", "匈牙利"}},
	{"🇮🇶", []string{"baghdad", "iraq", "伊拉克", "巴格达"}},
	{"🇯🇴", []string{"jordan", "约旦"}},
	{"🇯🇵", []string{"japan", "osaka", "tokyo", "东京", "埼玉", "大阪", "日本"}},
	{"🇰🇪", []string{"kenya", "肯尼亚"}},
	{"🇰🇬", []string{"kyrgyzstan", "吉尔吉斯斯坦"}},
	{"🇰🇭", []string{"cambodia", "柬埔寨"}},
	{"🇰🇵", []string{"north korea", "朝鲜"}},
	{"🇰🇷", []string{"chuncheon", "korea", "seoul", "春川", "韓", "韩", "首尔"}},
	{"🇰🇿", []string{"kazakhstan", "哈萨克"}},
	{"🇮🇩", []string{"indonesia", "印尼", "印度尼西亚", "雅加达"}},
	{"🇮🇪", []string{"ireland", "愛爾蘭", "爱尔兰", "都柏林"}},
	{"🇮🇱", []string{"israel", "以色列"}},
	{"🇮🇲", []string{"isle of man", "马恩岛"}},
	{"🇮🇳", []string{"india", "mumbai", "印度", "孟买"}},
	{"🇮🇷", []string{"iran", "伊朗"}},
	{"🇮🇸", []string{"iceland", "冰岛", "冰島"}},
	{"🇮🇹", []string{"italy", "意大利", "米兰", "義大利"}},
	{"🇱🇰", []string{"sri lanka", "斯里兰卡", "斯里蘭卡"}},
	{"🇱🇦", []string{"laos", "老挝"}},
	{"🇱🇸", []string{"lesotho", "莱索托"}},
	{"🇱🇹", []string{"lithuania", "立陶宛"}},
	{"🇱🇺", []string{"luxembourg", "卢森堡"}},
	{"🇱🇻", []string{"latvia", "拉脱维亚"}},
	{"🇲🇦", []string{"morocco", "摩洛哥"}},
	{"🇲🇩", []string{"moldova", "摩尔多瓦", "摩爾多瓦"}},
	{"🇲🇲", []string{"myanmar", "緬甸", "缅甸"}},
	{"🇳🇬", []string{"nigeria", "尼日利亚"}},
	{"🇲🇰", []string{"macedonia", "馬其頓", "马其顿"}},
	{"🇲🇳", []string{"mongolia", "蒙古"}},
	{"🇲🇴", []string{"ctm", "macao", "澳門", "澳门"}},
	{"🇲🇹", []string{"malta", "马耳他"}},
	{"🇲🇽", []string{"mexico", "墨西哥"}},
	{"🇲🇾", []string{"malaysia", "吉隆坡", "馬來", "马来"}},
	{"🇳🇱", []string{"amsterdam", "netherlands", "荷兰", "荷蘭", "阿姆斯特丹"}},
	{"🇳🇴", []string{"norway", "挪威"}},
	{"🇳🇵", []string{"nepal", "尼泊尔"}},
	{"🇳🇿", []string{"new zealand", "新西兰"}},
	{"🇴🇲", []string{"oman", "阿曼", "马斯喀特"}},
	{"🇵🇦", []string{"panama", "巴拿马"}},
	{"🇵🇪", []string{"peru", "秘鲁"}},
	{"🇵🇭", []string{"philippines", "菲律宾", "菲律賓"}},
	{"🇵🇰", []string{"pakistan", "巴基斯坦"}},
	{"🇵🇱", []string{"poland", "warsaw", "华沙", "波兰", "波蘭"}},
	{"🇵🇷", []string{"puerto rico", "波多黎各"}},
	{"🇵🇹", []string{"portugal", "葡萄牙"}},
	{"🇵🇬", []string{"papua new guinea", "巴布亚新几内亚"}},
	{"🇵🇾", []string{"paraguay", "巴拉圭"}},
	{"🇶🇦", []string{"qatar", "卡塔尔"}},
	{"🇷🇴", []string{"罗马尼亚"}},
	{"🇷🇸", []string{"serbia", "塞尔维亚"}},
	{"🇷🇪", []string{"réunion", "留尼汪"}},
	{"🇷🇺", []string{"moscow", "russia", "伯力", "俄罗斯", "俄羅斯", "圣彼得堡", "莫斯科", "西伯利亚"}},
	{"🇸🇦", []string{"riyadh", "saudi", "利雅得", "沙特"}},
	{"🇸🇪", []string{"stockholm", "sweden", "斯德哥尔摩", "瑞典"}},
	{"🇸🇬", []string{"singapore", "新加坡", "狮城"}},
	{"🇸🇮", []string{"slovenia", "斯洛文尼亚"}},
	{"🇸🇰", []string{"slovakia", "斯洛伐克"}},
	{"🇹🇬", []string{"lome", "togo", "多哥"}},
	{"🇹🇭", []string{"thailand", "曼谷", "泰国", "泰國"}},
	{"🇹🇳", []string{"tunisia", "突尼斯"}},
	{"🇹🇷", []string{"istanbul", "伊斯坦布尔", "土耳其"}},
	{"🇹🇼", []string{"taipei", "taiwan", "中华民国", "台", "彰化", "新北", "臺"}},
	{"🇺🇦", []string{"ukraine", "乌克兰", "烏克蘭"}},
	{"🇺🇸", []string{"america", "los angeles", "michigan", "new york", "ohio", "oregon", "san jose", "united states", "virginia", "俄亥俄", "俄勒冈", "凤凰城", "哥伦布", "圣何塞", "圣克拉拉", "弗吉尼亚", "拉斯维加斯", "波特兰", "洛杉矶", "硅谷", "纽约", "美", "芝加哥", "西雅图", "达拉斯"}},
	{"🇺🇾", []string{"uruguay", "乌拉圭"}},
	{"🇻🇦", []string{"vatican", "梵蒂冈", "梵蒂岡"}},
	{"🇻🇪", []string{"venezuela", "委内瑞拉"}},
	{"🇻🇳", []string{"vietnam", "胡志明", "越南"}},
	{"🇿🇦", []string{"south africa", "南非"}},
	{"🇨🇳", []string{"china", "上海", "中国", "中國", "北京", "宁波", "广州", "杭州", "深圳", "青岛"}},
}

var flagCodes = []struct {
	flag  string
	codes []string
}{
	{"🏳️‍🌈", []string{"EXP"}},
	{"🇸🇱", []string{"SOS"}},
	{"🇲🇵", []string{"MNP", "MP"}},
	{"🇸🇴", []string{"SO", "SOM"}},
	{"🇦🇶", []string{"AQ", "ATA"}},
	{"🇦🇬", []string{"AG", "ATG"}},
	{"🇬🇱", []string{"GL", "GRL"}},
	{"🇿🇼", []string{"ZW", "ZWE"}},
	{"🇦🇼", []string{"ABW", "AW"}},
	{"🇲🇱", []string{"ML", "MLI"}},
	{"🇦🇩", []string{"AD", "AND"}},
	{"🇦🇪", []string{"AE", "ARE"}},
	{"🇦🇫", []string{"AF", "AFG"}},
	{"🇦🇱", []string{"AL", "ALB"}},
	{"🇦🇲", []string{"AM", "ARM"}},
	{"🇦🇷", []string{"AR", "ARG"}},
	{"🇦🇹", []string{"AT", "AUT"}},
	{"🇦🇺", []string{"AU", "AUS"}},
	{"🇦🇿", []string{"AZ", "AZE"}},
	{"🇧🇦", []string{"BA", "BIH"}},
	{"🇧🇩", []string{"BD", "BGD"}},
	{"🇧🇪", []string{"BE", "BEL"}},
	{"🇧🇬", []string{"BG", "BGR"}},
	{"🇧🇭", []string{"BH", "BHR"}},
	{"🇧🇴", []string{"BO", "BOL"}},
	{"🇧🇳", []string{"BN", "BRN"}},
	{"🇧🇷", []string{"BR", "BRA"}},
	{"🇧🇹", []string{"BT", "BTN"}},
	{"🇧🇾", []string{"BLR", "BY"}},
	{"🇨🇦", []string{"CA", "CAN"}},
	{"🇨🇫", []string{"CAF", "CF"}},
	{"🇨🇭", []string{"CH", "CHE"}},
	{"🇨🇱", []string{"CHL", "CL"}},
	{"🇨🇴", []string{"CO", "COL"}},
	{"🇨🇷", []string{"CR", "CRI"}},
	{"🇨🇾", []string{"CY", "CYP"}},
	{"🇨🇿", []string{"CZ", "CZE"}},
	{"🇩🇪", []string{"DE", "DEU"}},
	{"🇩🇰", []string{"DK", "DNK"}},
	{"🇩🇿", []string{"DZ", "DZA"}},
	{"🇪🇨", []string{"EC", "ECU"}},
	{"🇪🇪", []string{"EE", "EST"}},
	{"🇪🇬", []string{"EG", "EGY"}},
	{"🇪🇸", []string{"ES", "ESP"}},
	{"🇪🇺", []string{"EU"}},
	{"🇫🇮", []string{"FI", "FIN"}},
	{"🇫🇷", []string{"FR", "FRA"}},
	{"🇬🇧", []string{"GB", "GBR", "UK"}},
	{"🇬🇪", []string{"GE", "GEO"}},
	{"🇬🇷", []string{"GR", "GRC"}},
	{"🇬🇹", []string{"GT", "GTM"}},
	{"🇬🇺", []string{"GU", "GUM"}},
	{"🇭🇰", []string{"CMI", "HGC", "HK", "HKBN", "HKG", "HKT", "WTT"}},
	{"🇭🇷", []string{"HR", "HRV"}},
	{"🇭🇺", []string{"HU", "HUN"}},
	{"🇮🇶", []string{"IQ", "IRQ"}},
	{"🇯🇴", []string{"JO", "JOR"}},
	{"🇯🇵", []string{"JP", "JPN", "TYO"}},
	{"🇰🇪", []string{"KE", "KEN"}},
	{"🇰🇬", []string{"KG", "KGZ"}},
	{"🇰🇭", []string{"KH"}},
	{"🇰🇵", []string{"KP", "PRK"}},
	{"🇰🇷", []string{"KOR", "KR", "SEL"}},
	{"🇰🇿", []string{"KAZ", "KZ"}},
	{"🇮🇩", []string{"ID", "IDN"}},
	{"🇮🇪", []string{"IE", "IRL"}},
	{"🇮🇱", []string{"IL", "ISR"}},
	{"🇮🇲", []string{"IM", "IMN"}},
	{"🇮🇳", []string{"IN", "IND"}},
	{"🇮🇷", []string{"IR", "IRN"}},
	{"🇮🇸", []string{"IS", "ISL"}},
	{"🇮🇹", []string{"IT", "ITA"}},
	{"🇱🇦", []string{"LA", "LAO"}},
	{"🇱🇰", []string{"LK", "LKA"}},
	{"🇱🇸", []string{"LS", "LSO"}},
	{"🇱🇹", []string{"LT", "LTU"}},
	{"🇱🇺", []string{"LU", "LUX"}},
	{"🇱🇻", []string{"LV", "LVA"}},
	{"🇲🇦", []string{"MA", "MAR"}},
	{"🇲🇩", []string{"MD", "MDA"}},
	{"🇳🇬", []string{"NG", "NGA"}},
	{"🇲🇲", []string{"MM", "MMR"}},
	{"🇲🇰", []string{"MK", "MKD"}},
	{"🇲🇳", []string{"MN", "MNG"}},
	{"🇲🇴", []string{"MAC", "MO"}},
	{"🇲🇹", []string{"MLT", "MT"}},
	{"🇲🇽", []string{"MEX", "MX"}},
	{"🇲🇾", []string{"MY", "MYS"}},
	{"🇳🇱", []string{"AMS", "NL", "NLD"}},
	{"🇳🇴", []string{"NO", "NOR"}},
	{"🇳🇵", []string{"NP", "NPL"}},
	{"🇳🇿", []string{"NZ", "NZL"}},
	{"🇴🇲", []string{"OM", "OMN"}},
	{"🇵🇦", []string{"PA", "PAN"}},
	{"🇵🇪", []string{"PE", "PER"}},
	{"🇵🇭", []string{"PH", "PHL"}},
	{"🇵🇰", []string{"PAK", "PK"}},
	{"🇵🇱", []string{"PL", "POL"}},
	{"🇵🇷", []string{"PR", "PRI"}},
	{"🇵🇹", []string{"PRT", "PT"}},
	{"🇵🇾", []string{"PRY", "PY"}},
	{"🇵🇬", []string{"PG", "PNG"}},
	{"🇶🇦", []string{"QA", "QAT"}},
	{"🇷🇴", []string{"RO", "ROU"}},
	{"🇷🇸", []string{"RS", "SRB"}},
	{"🇷🇪", []string{"RE", "REU"}},
	{"🇷🇺", []string{"RU", "RUS"}},
	{"🇸🇦", []string{"SA", "SAU"}},
	{"🇼🇸", []string{"WS", "WSM"}},
	{"🇸🇪", []string{"SE", "SWE"}},
	{"🇸🇬", []string{"SG", "SGP"}},
	{"🇸🇮", []string{"SI", "SVN"}},
	{"🇸🇰", []string{"SK", "SVK"}},
	{"🇹🇬", []string{"TG", "TGO"}},
	{"🇹🇭", []string{"TH", "THA"}},
	{"🇹🇳", []string{"TN", "TUN"}},
	{"🇹🇷", []string{"TR", "TUR"}},
	{"🇹🇼", []string{"CHT", "ROC", "TW", "TWN"}},
	{"🇺🇦", []string{"UA", "UKR"}},
	{"🇺🇸", []string{"LAX", "SFO", "SJC", "US", "USA"}},
	{"🇺🇾", []string{"URY", "UY"}},
	{"🇻🇦", []string{"VA", "VAT"}},
	{"🇻🇪", []string{"VE", "VEN"}},
	{"🇻🇳", []string{"VN", "VNM"}},
	{"🇿🇦", []string{"JNB", "ZA", "ZAF"}},
	{"🇨🇳", []string{"CHN", "CN"}},
}
